# Oracle V4 - GPU-Accelerated Hurricane Simulation
# 
#  STRONGLY RECOMMENDED: Use conda for installation 
# This ensures proper CUDA toolkit integration and GPU acceleration
# 
# Quick start:
#   conda env create -f environment.yml
#   conda activate oracle_env
#
#  GPU Performance: ~23x faster than CPU-only installations
#  Tested with NVIDIA CUDA 12.x/13.x
#  Requires NVIDIA GPU with compute capability 6.0+

name: oracle_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - affine=2.4.0=pyhd8ed1ab_1
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.12.15=py311h3f79411_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - aom=3.9.1=he0c23c2_0
  - apptools=5.3.1=pyhe01879c_1
  - attrs=25.3.0=pyh71513ae_0
  - beautifulsoup4=4.13.5=pyha770c72_0
  - blosc=1.21.6=hfd34d9b_1
  - brotli=1.1.0=h2466b09_3
  - brotli-bin=1.1.0=h2466b09_3
  - brotli-python=1.1.0=py311hda3d55a_3
  - bzip2=1.0.8=h2466b09_7
  - ca-certificates=2025.11.12=h4c7d964_0
  - cairo=1.18.4=h5782bbf_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=1.17.1=py311he736701_0
  - cfgrib=0.9.15.0=pyhd8ed1ab_0
  - cftime=1.6.4=py311h0a17f05_1
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - click=8.2.1=pyh7428d3b_0
  - click-plugins=1.1.1.2=pyhd8ed1ab_0
  - cligj=0.7.2=pyhd8ed1ab_2
  - colorama=0.4.6=pyhd8ed1ab_1
  - configobj=5.0.9=pyhd8ed1ab_1
  - contourpy=1.3.3=py311h3fd045d_1
  - cuda-cccl_win-64=13.0.85=h57928b3_0
  - cuda-cudart-dev_win-64=13.0.96=hac47afa_0
  - cuda-cudart-static_win-64=13.0.96=hac47afa_0
  - cuda-cudart_win-64=13.0.96=hac47afa_0
  - cuda-nvrtc=13.0.88=hac47afa_0
  - cuda-version=13.0=hc7b4dd1_3
  - cupy=13.6.0=py311h51cb6b0_2
  - cupy-core=13.6.0=py311ha034cfd_2
  - cycler=0.12.1=pyhd8ed1ab_1
  - dav1d=1.2.1=hcfcfb64_0
  - double-conversion=3.3.1=he0c23c2_0
  - eccodes=2.42.0=hb4e25be_0
  - envisage=7.0.4=pyhe01879c_1
  - fastrlock=0.8.3=py311h5dfdfe8_2
  - ffmpeg=7.1.1=gpl_h70aa942_909
  - findlibs=0.1.2=pyhd8ed1ab_0
  - fmt=11.2.0=h1d4551f_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.59.1=py311h3f79411_0
  - freeglut=3.2.2=he0c23c2_3
  - freetype=2.13.3=h57928b3_1
  - freexl=2.0.0=hf297d47_2
  - fribidi=1.0.10=h8d14728_0
  - frozenlist=1.7.0=py311hdf60d3a_0
  - gdk-pixbuf=2.42.12=h1f5b9c4_3
  - geos=3.13.1=h9ea8674_0
  - geotiff=1.7.4=h86c3423_2
  - gl2ps=1.4.2=had7236b_1
  - glib=2.84.3=h36503ca_0
  - glib-tools=2.84.3=he647baa_0
  - graphite2=1.3.14=hac47afa_2
  - gst-plugins-base=1.24.11=h3fe0a9e_0
  - gstreamer=1.24.11=h233a61a_0
  - h2=4.2.0=pyhd8ed1ab_0
  - harfbuzz=11.4.4=h5f2951f_0
  - hdf4=4.2.15=h5557f11_7
  - hdf5=1.14.6=nompi_he30205f_103
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he0c23c2_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - jasper=4.2.8=h8ad263b_0
  - jsoncpp=1.9.6=hda1637e_1
  - kiwisolver=1.4.9=py311h275cad7_0
  - krb5=1.21.3=hdf4eb48_0
  - lame=3.100=hcfcfb64_1003
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libaec=1.1.4=h20038f6_0
  - libarchive=3.8.1=gpl_h1ca5a36_100
  - libblas=3.9.0=34_h5709861_mkl
  - libbrotlicommon=1.1.0=h2466b09_3
  - libbrotlidec=1.1.0=h2466b09_3
  - libbrotlienc=1.1.0=h2466b09_3
  - libcblas=3.9.0=34_h2a3cdd5_mkl
  - libclang13=20.1.8=default_hadf22e1_0
  - libcublas=13.1.0.3=hac47afa_0
  - libcufft=12.0.0.61=hac47afa_0
  - libcurand=10.4.0.35=hac47afa_1
  - libcurl=8.14.1=h88aaa65_0
  - libcusolver=12.0.4.66=hac47afa_1
  - libcusparse=12.6.3.3=hac47afa_0
  - libdeflate=1.24=h76ddb4d_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.6=h537db12_1
  - libfreetype=2.13.3=h57928b3_1
  - libfreetype6=2.13.3=h0b5ce68_1
  - libgcc=15.1.0=h1383e82_4
  - libgdal-core=3.10.3=h228a343_13
  - libglib=2.84.3=h1c1036b_0
  - libgomp=15.1.0=h1383e82_4
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.0=h2466b09_0
  - libkml=1.3.0=h538826c_1021
  - liblapack=3.9.0=34_hf9ab0e9_mkl
  - liblzma=5.8.1=h2466b09_2
  - libnetcdf=4.9.2=nompi_ha45073a_118
  - libnvjitlink=13.0.88=hac47afa_0
  - libogg=1.3.5=h2466b09_1
  - libopus=1.5.2=h2466b09_0
  - libpng=1.6.50=h7351971_1
  - librsvg=2.58.4=h5ce5fed_3
  - librttopo=1.1.0=hbfc9ebc_18
  - libspatialite=5.1.0=h378fb81_14
  - libsqlite=3.50.4=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libtheora=1.1.1=hc70643c_1006
  - libtiff=4.7.0=h550210a_6
  - libusb=1.0.29=h1839187_0
  - libvorbis=1.3.7=h5112557_2
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_9
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.8=h741aa76_1
  - libxslt=1.1.43=h25c3957_0
  - libzip=1.11.2=h3135430_0
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=20.1.8=hfa2b4ca_2
  - loguru=0.7.3=pyh7428d3b_0
  - lz4-c=1.10.0=h2466b09_1
  - lzo=2.10=h6a83c73_1002
  - matplotlib=3.10.5=py311h1ea47a8_0
  - matplotlib-base=3.10.5=py311h1675fdf_0
  - mayavi=4.8.3=pyqt_py311h306cd62_301
  - minizip=4.0.10=h9fa1bad_0
  - mkl=2024.2.2=h57928b3_16
  - msgpack-python=1.1.1=py311h3257749_0
  - multidict=6.6.3=py311h3f79411_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - netcdf4=1.7.2=nompi_py311he84594c_103
  - nlohmann_json=3.12.0=he0c23c2_0
  - numpy=2.3.2=py311haedcf98_1
  - openh264=2.6.0=hb17fa0b_0
  - openjpeg=2.5.3=h24db6dd_1
  - openssl=3.6.0=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311h11fd7f3_1
  - pango=1.56.4=h03d888a_0
  - pcre2=10.45=h99c9b8b_0
  - pillow=11.3.0=py311h0f9b5fc_0
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h5112557_1
  - platformdirs=4.4.0=pyhcf101f3_0
  - ply=3.11=pyhd8ed1ab_3
  - pooch=1.8.2=pyhd8ed1ab_3
  - proj=9.6.2=h7990399_2
  - propcache=0.3.1=py311h5082efb_0
  - protobuf=6.31.1=py311heca59f8_0
  - pthread-stubs=0.4=h0e40799_1002
  - pugixml=1.15=h372dad0_0
  - pycparser=2.22=pyh29332c3_1
  - pyface=8.0.0=pyhd8ed1ab_2
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhe01879c_2
  - pyqt=5.15.11=py311h2d05f59_1
  - pyqt5-sip=12.17.0=py311hda3d55a_1
  - pyside6=6.9.1=py311h5d1a980_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.11.13=h3f84c4b_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-eccodes=2.37.0=py311h0a17f05_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=8_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - pyvista=0.46.3=pyhd8ed1ab_0
  - qhull=2020.2=hc790b64_5
  - qt-main=5.15.15=hb098fff_5
  - qt6-main=6.9.1=h02ddd7d_2
  - rasterio=1.4.3=py311hf7d2747_1
  - requests=2.32.5=pyhd8ed1ab_0
  - scooby=0.10.1=pyhd8ed1ab_0
  - sdl2=2.32.54=he0c23c2_0
  - sdl3=3.2.20=h5112557_0
  - setuptools=80.9.0=pyhff2d567_0
  - sip=6.10.0=py311hda3d55a_0
  - siphon=0.10.0=pyhd8ed1ab_1
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h7fa0ca8_0
  - snuggs=1.4.7=pyhd8ed1ab_2
  - soupsieve=2.7=pyhd8ed1ab_0
  - sqlite=3.50.4=hdb435a2_0
  - svt-av1=3.1.2=hac47afa_0
  - tbb=2021.13.0=h18a62a1_3
  - tk=8.6.13=h2c6b04d_2
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.2.1=pyhe01879c_2
  - tornado=6.5.2=py311h3485c13_0
  - traits=7.0.2=py311he736701_0
  - traitsui=8.0.0=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.22621.0=h57928b3_1
  - unicodedata2=16.0.0=py311he736701_0
  - uriparser=0.9.8=h5a68840_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - utfcpp=4.0.6=hc1507ef_0
  - vc=14.3=h41ae7f8_31
  - vc14_runtime=14.44.35208=h818238b_31
  - vcomp14=14.44.35208=h818238b_31
  - vs2015_runtime=14.44.35208=h38c0c73_31
  - vtk-base=9.4.2=py311h6afd1d8_3
  - wheel=0.45.1=pyhd8ed1ab_1
  - win32_setctime=1.2.0=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - wslink=2.4.0=pyhd8ed1ab_0
  - x264=1!164.3095=h8ffe710_2
  - x265=3.5=h2d74725_3
  - xarray=2025.11.0=pyhcf101f3_0
  - xerces-c=3.2.5=he0c23c2_2
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - yarl=1.20.1=py311h5082efb_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h2466b09_2
  - zstandard=0.23.0=py311h3485c13_3
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - cdsapi==0.7.6
      - cupy-cuda12x==13.6.0
      - cupy-cuda13x==13.6.0
      - ecmwf-datastores-client==0.4.0
      - geographiclib==2.1
      - geojson==3.2.0
      - geopandas==1.1.1
      - geopy==2.4.1
      - multiurl==0.3.7
      - pyogrio==0.11.1
      - pyproj==3.7.2
      - scipy==1.16.3
      - shapely==2.1.1
      - tqdm==4.67.1
prefix: C:\Users\itali\miniconda3\envs\oracle_env
